/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ItemlistRouteImport } from './routes/itemlist'
import { Route as CatalogsRouteImport } from './routes/catalogs'
import { Route as BoxlistRouteImport } from './routes/boxlist'
import { Route as BoxesRouteImport } from './routes/boxes'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItemsIndexRouteImport } from './routes/items/index'
import { Route as GroupsIndexRouteImport } from './routes/groups/index'
import { Route as GroupsGroupIdRouteImport } from './routes/groups/$groupId'
import { Route as BoxesBoxIdRouteImport } from './routes/boxes.$boxId'
import { Route as ApiItemsRouteImport } from './routes/api/items'
import { Route as ApiBoxesRouteImport } from './routes/api/boxes'

const ItemlistRoute = ItemlistRouteImport.update({
  id: '/itemlist',
  path: '/itemlist',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogsRoute = CatalogsRouteImport.update({
  id: '/catalogs',
  path: '/catalogs',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxlistRoute = BoxlistRouteImport.update({
  id: '/boxlist',
  path: '/boxlist',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxesRoute = BoxesRouteImport.update({
  id: '/boxes',
  path: '/boxes',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIndexRoute = ItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxesBoxIdRoute = BoxesBoxIdRouteImport.update({
  id: '/$boxId',
  path: '/$boxId',
  getParentRoute: () => BoxesRoute,
} as any)
const ApiItemsRoute = ApiItemsRouteImport.update({
  id: '/api/items',
  path: '/api/items',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBoxesRoute = ApiBoxesRouteImport.update({
  id: '/api/boxes',
  path: '/api/boxes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/boxes': typeof BoxesRouteWithChildren
  '/boxlist': typeof BoxlistRoute
  '/catalogs': typeof CatalogsRoute
  '/itemlist': typeof ItemlistRoute
  '/api/boxes': typeof ApiBoxesRoute
  '/api/items': typeof ApiItemsRoute
  '/boxes/$boxId': typeof BoxesBoxIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups': typeof GroupsIndexRoute
  '/items': typeof ItemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/boxes': typeof BoxesRouteWithChildren
  '/boxlist': typeof BoxlistRoute
  '/catalogs': typeof CatalogsRoute
  '/itemlist': typeof ItemlistRoute
  '/api/boxes': typeof ApiBoxesRoute
  '/api/items': typeof ApiItemsRoute
  '/boxes/$boxId': typeof BoxesBoxIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups': typeof GroupsIndexRoute
  '/items': typeof ItemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/boxes': typeof BoxesRouteWithChildren
  '/boxlist': typeof BoxlistRoute
  '/catalogs': typeof CatalogsRoute
  '/itemlist': typeof ItemlistRoute
  '/api/boxes': typeof ApiBoxesRoute
  '/api/items': typeof ApiItemsRoute
  '/boxes/$boxId': typeof BoxesBoxIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/': typeof GroupsIndexRoute
  '/items/': typeof ItemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/boxes'
    | '/boxlist'
    | '/catalogs'
    | '/itemlist'
    | '/api/boxes'
    | '/api/items'
    | '/boxes/$boxId'
    | '/groups/$groupId'
    | '/groups'
    | '/items'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/boxes'
    | '/boxlist'
    | '/catalogs'
    | '/itemlist'
    | '/api/boxes'
    | '/api/items'
    | '/boxes/$boxId'
    | '/groups/$groupId'
    | '/groups'
    | '/items'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/boxes'
    | '/boxlist'
    | '/catalogs'
    | '/itemlist'
    | '/api/boxes'
    | '/api/items'
    | '/boxes/$boxId'
    | '/groups/$groupId'
    | '/groups/'
    | '/items/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BoxesRoute: typeof BoxesRouteWithChildren
  BoxlistRoute: typeof BoxlistRoute
  CatalogsRoute: typeof CatalogsRoute
  ItemlistRoute: typeof ItemlistRoute
  ApiBoxesRoute: typeof ApiBoxesRoute
  ApiItemsRoute: typeof ApiItemsRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  ItemsIndexRoute: typeof ItemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/itemlist': {
      id: '/itemlist'
      path: '/itemlist'
      fullPath: '/itemlist'
      preLoaderRoute: typeof ItemlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogs': {
      id: '/catalogs'
      path: '/catalogs'
      fullPath: '/catalogs'
      preLoaderRoute: typeof CatalogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boxlist': {
      id: '/boxlist'
      path: '/boxlist'
      fullPath: '/boxlist'
      preLoaderRoute: typeof BoxlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boxes': {
      id: '/boxes'
      path: '/boxes'
      fullPath: '/boxes'
      preLoaderRoute: typeof BoxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/': {
      id: '/items/'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boxes/$boxId': {
      id: '/boxes/$boxId'
      path: '/$boxId'
      fullPath: '/boxes/$boxId'
      preLoaderRoute: typeof BoxesBoxIdRouteImport
      parentRoute: typeof BoxesRoute
    }
    '/api/items': {
      id: '/api/items'
      path: '/api/items'
      fullPath: '/api/items'
      preLoaderRoute: typeof ApiItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/boxes': {
      id: '/api/boxes'
      path: '/api/boxes'
      fullPath: '/api/boxes'
      preLoaderRoute: typeof ApiBoxesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BoxesRouteChildren {
  BoxesBoxIdRoute: typeof BoxesBoxIdRoute
}

const BoxesRouteChildren: BoxesRouteChildren = {
  BoxesBoxIdRoute: BoxesBoxIdRoute,
}

const BoxesRouteWithChildren = BoxesRoute._addFileChildren(BoxesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BoxesRoute: BoxesRouteWithChildren,
  BoxlistRoute: BoxlistRoute,
  CatalogsRoute: CatalogsRoute,
  ItemlistRoute: ItemlistRoute,
  ApiBoxesRoute: ApiBoxesRoute,
  ApiItemsRoute: ApiItemsRoute,
  GroupsGroupIdRoute: GroupsGroupIdRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  ItemsIndexRoute: ItemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
